import axios from 'axios';
import { addAttraction } from './attractionsDB';
import { createAttractionLayer } from './attractionLayer';
import $ from 'jquery';
window.$ = $;

const apiURL = 'https://overpass-api.de/api/interpreter?data=';

/**
 * Makes a GET request to Overpass API using the provided overpass Query and adds the data to Indexed DB.
 *
 * @param {String} overpassQuery overpass query to retrieve data
 */
const getMallData = async (overpassQuery) => {
	try {
		const response = await axios({
			method: 'get',
			url: apiURL + encodeURIComponent(overpassQuery),
		});
		const data = response.data;
		await addAttraction({ key: 'mall', data: data }, 'mall');
	} catch (error) {
		console.error('Error while retrieving data from OSM: ', error);
	}
};

/*
The query below will return malls from London.
This has been generated by the overpass-turbo wizard.
*/
const mallQuery = `
area(id:3600065606)->.searchArea;
nwr['shop'='mall'](area.searchArea);
out geom;
`;

/**
 * Queries database for mall data and creates a layer with icons representing attraction locations.
 */
const createMallLayer = async () => {
	await getMallData(mallQuery);
	await createAttractionLayer('mall');
};

$(document).on('ready', createMallLayer());
