import axios from 'axios';
import { addAttraction } from './attractionsDB';
import { createAttractionLayer } from './attractionLayer';
import $ from 'jquery';
window.$ = $;

const apiURL = 'https://overpass-api.de/api/interpreter?data=';

/**
 * Makes a GET request to Overpass API using the provided overpass Query and adds the data to Indexed DB.
 *
 * @param {String} overpassQuery overpass query to retrieve data
 */
const getTheatreData = async (overpassQuery) => {
	try {
		const response = await axios({
			method: 'get',
			url: apiURL + encodeURIComponent(overpassQuery),
		});
		const data = response.data;
		await addAttraction({ key: 'theatre', data: data }, 'theatre');
	} catch (error) {
		console.error('Error while retrieving data from OSM: ', error);
	}
};

/*
The query below will return theatres from London.
This has been generated by the overpass-turbo wizard.
*/
const theatreQuery = `
area(id:3600065606)->.searchArea;
nwr['amenity'='theatre'](area.searchArea);
out geom;
`;

/**
 * Queries theatre data from IndexedDB and creates a layer with cafe icons representing the attraction locations.
 */
const createTheatreLayer = async () => {
	await getTheatreData(theatreQuery);
	await createAttractionLayer('theatre');
};

$(document).on('ready', createTheatreLayer());
